import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary": "#690100",
        "background": "#131313",
        "on-secondary-container": "#ff9f90",
        "tertiary-fixed-dim": "#acc7ff",
        "secondary-fixed": "#ffdad4",
        "secondary-container": "#970100",
        "primary-fixed-dim": "#ffb4a8",
        "tertiary": "#acc7ff",
        "on-primary-container": "#5c0000",
        "on-secondary-fixed": "#410000",
        "surface-variant": "#353534",
        "surface-tint": "#ffb4a8",
        "on-primary-fixed-variant": "#930100",
        "secondary": "#ffb4a8",
        "on-tertiary": "#002f67",
        "surface-container-lowest": "#0e0e0e",
        "on-tertiary-fixed": "#001a40",
        "tertiary-container": "#488fff",
        "outline": "#b18780",
        "on-background": "#e5e2e1",
        "tertiary-fixed": "#d7e2ff",
        "on-surface-variant": "#ebbbb4",
        "on-tertiary-fixed-variant": "#004491",
        "surface-container": "#201f1f",
        "surface-bright": "#3a3939",
        "primary-fixed": "#ffdad4",
        "inverse-on-surface": "#313030",
        "on-error": "#690005",
        "surface-container-high": "#2a2a2a",
        "secondary-fixed-dim": "#ffb4a8",
        "surface-dim": "#131313",
        "on-primary": "#690100",
        "inverse-primary": "#c00100",
        "primary-container": "#ff5540",
        "on-secondary-fixed-variant": "#930100",
        "inverse-surface": "#e5e2e1",
        "error-container": "#93000a",
        "surface": "#131313",
        "primary": "#ffb4a8",
        "on-primary-fixed": "#410000",
        "outline-variant": "#603e39",
        "on-tertiary-container": "#00285b",
        "error": "#ffb4ab",
        "surface-container-highest": "#353534",
        "on-surface": "#e5e2e1",
        "surface-container-low": "#1c1b1b",
        "on-error-container": "#ffdad6"
      },
      fontFamily: {
        "headline": ["var(--font-space-grotesk)"],
        "body": ["var(--font-inter)"],
        "label": ["var(--font-space-mono)"]
      },
      borderRadius: { "DEFAULT": "0px", "lg": "0px", "xl": "0px", "full": "9999px" },
    },
  },
  plugins: [],
};
export default config;
